### ISSUE TITLE
Simple Scope:  no controls mode?

### ISSUE THREAD

**Issue by unfa** [x42/meters.lv2#11]
The Stereo Phase Scope has an options panel that is hidden by default and can be shown if needed.

I think it might be useful to hide the Simple Scopes settings and extra information below (marked red) at will:

![sisco](https://cloud.githubusercontent.com/assets/491704/9291175/9579b01e-43b1-11e5-9f20-b3c83b48ae25.png)

This could allow to save some screen space when the user doesn't need so much info and tweaking the settings at the moment.

**Comment by x42** [comment]
That should go to  https://github.com/x42/sisco.lv2/ it's not part of meters.lv2

Note however that it is an oscilloscope the controls and numeric readout are essential.
If you want some simple waveform-viewer this is not the project to use.

The goniometer on the other hand is useful for live-production. It is not an instrumentation tool and  the setup is only for advanced cases (and hence hidden).
