### ISSUE TITLE
EBUrLV2 error: Host does not support urid:map

### ISSUE THREAD

**Issue by brummer10** [x42/meters.lv2#12]
ebulv2 and goniometerlv2 needs LV2_URID__map, but didn't announce that in the ttl file as requested feature. That leads to a crash in guitarix, because guitarix didn't support LV2_URID__map. Please use 
lv2:requiredFeature urid:map 
in the respective ttl file. 

regards
hermann

**Comment by x42** [comment]
Thanks. The goniometer indeed lacks this.

But the EBUr128 meter has support for this:
https://github.com/x42/meters.lv2/blob/master/lv2ttl/meters.lv2.ttl.in#L588
and instantiation will fail in either case if the host does not support urid:map.
