### ISSUE TITLE
add lv2:optionalFeature idisp:queue_draw and lv2:extensionData idisp:interface to *.ttl where appropriate

### ISSUE THREAD

**Issue by ventosus** [x42/meters.lv2#17]
Title says it. Hosts supporting the inlinedisplay extension but relying on proper advertising of its support plugin-wise won't be able to show any fancy graphs

**Comment by x42** [comment]
I'm somewhat reluctant to do that because there's no official and no stable URI prefix.

**Comment by x42** [comment]
oops.  https://github.com/x42/lv2/blob/master-rg/lv2/ardour.org/ns/ext/inline-display/lv2-inline-display.doap.ttl   says "1.0",  I suppose that's stable :)
