### ISSUE TITLE
Crash with multiple meters (in Carla host)

### ISSUE THREAD

**Issue by BlueMax** [x42/meters.lv2#25]
When i have two 'UV meters' open in custom gui they run for some seconds and then crash/freeze Carla (no screen/window updates, sound continues properly). This also happens when i add/remove/add another x42 plugin. It doesn't happen if i 'replace' the plugin. It works properly if i just add one plugin and keep it. Other plugins (non-x42) work fine with multiple instances/plugins.

The bug itself seems xorg or nouveau related. Sometimes just the Carla window freezes, sometimes the whole graphic backend/keyboard (x11?) is frozen. I can always SSH into the machine and kill Carla though and get the system back.

Here is a [log fragment](https://pastebin.com/raw/mqBtfPsd).

Any idea what could be wrong?

Linux 5.2.0-arch2-1-ARCH SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux
jack2-dbus 1.9.12
x42-plugins 20190714
carla 2.0.0
cadence 0.9.0
nouveau kms + glamor (GTX770/NVE0)
xorg-server 1.20.5
mesa 19.1.2

![Carla](https://user-images.githubusercontent.com/1403092/61191446-23197480-a6ab-11e9-92c7-d1273d07f4bd.png)

**Comment by x42** [comment]
It's a known issue that Nvidia + nouveau-driver does not support multiple client windows in a single application.

This is not limited to Carla and LV2 GUIs - same issue happens with other plugins-hosts (e.g. Ardour) and all openGL plugin UIs in separate windows

The nvidia-binary driver handles this correctly.

**Comment by BlueMax** [comment]
Thanks!

**Comment by BlueMax** [comment]
Looks like the **nouveau.noaccel=1** kernel parameter helps here. No crashes.
Env variable **QT_XCB_FORCE_SOFTWARE_OPENGL=1** did not help.
https://wiki.archlinux.org/index.php/Nouveau#Random_lockups_with_kernel_error_messages
