### ISSUE TITLE
build fails on Big Sur

### ISSUE THREAD

**Issue by andistern** [x42/meters.lv2#32]
had to 
export RW=robtk/
after make submodules ( documentation issue ?) to find robtk
finally failed with

c++ -I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl@1.1/include  -Wall -Wno-unused-function -g -msse -msse2 -mfpmath=sse -fomit-frame-pointer -O3 -fno-finite-math-only -DNDEBUG -DXTERNAL_UI -DHAVE_LV2_1_8 -fPIC -fvisibility=hidden `pkg-config --cflags lv2` -DVERSION="\"0.9.18-2\"" -I. -DHAVE_IDLE_IFACE `pkg-config --cflags cairo pango`  -DUSE_GUI_THREAD -pthread \
	  -o build/meters_glui.dylib gui/meters.c \
	  obj/pugl.o obj/needleUI_gl.o obj/eburUI_gl.o obj/goniometerUI_gl.o obj/dpmUI_gl.o obj/kmeterUI_gl.o obj/phasewheelUI_gl.o obj/stereoscopeUI_gl.o obj/dr14meterUI_gl.o obj/sdhmeterUI_gl.o obj/bitmeterUI_gl.o obj/surmeterUI_gl.o \
	  `pkg-config --cflags --libs fftw3f` -lm zita-resampler/resampler.cc zita-resampler/resampler-table.cc \
	  -shared -dynamiclib -L/usr/local/opt/bzip2/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib  -framework Cocoa -framework OpenGL `pkg-config --libs  cairo pangocairo pango ` 
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: error: no such file or directory: 'obj/pugl.o'
clang: error: no such file or directory: 'obj/needleUI_gl.o'
clang: error: no such file or directory: 'obj/eburUI_gl.o'
clang: error: no such file or directory: 'obj/goniometerUI_gl.o'
clang: error: no such file or directory: 'obj/dpmUI_gl.o'
clang: error: no such file or directory: 'obj/kmeterUI_gl.o'
clang: error: no such file or directory: 'obj/phasewheelUI_gl.o'
clang: error: no such file or directory: 'obj/stereoscopeUI_gl.o'
clang: error: no such file or directory: 'obj/dr14meterUI_gl.o'
clang: error: no such file or directory: 'obj/sdhmeterUI_gl.o'
clang: error: no such file or directory: 'obj/bitmeterUI_gl.o'
clang: error: no such file or directory: 'obj/surmeterUI_gl.o'
make: *** [build/meters_glui.dylib] Error 1

Did I miss something?

**Comment by x42** [comment]
> Did I miss something?

The build log for all the object files (.o) is not shown. Compile works here on BigSur.

ARM/M1 binaries are available from https://x42-plugins.com/x42/mac/x42-meters-v0.9.18-arm64.pkg

**Comment by andistern** [comment]
... tried x42-meters-v0.9.18.pkg ...
obj directory does not exists - suspect that object. files (.o) are not created ;-))

**Comment by x42** [comment]
> obj directory does not exists - suspect that object. files (.o) are not created ;-))

This is odd. maybe a GNU-make vs BSD/Apple-make difference? `which make` are you using, is that from homebrew?

It's clearly there in the makefile and listed as dependencies:

https://github.com/x42/meters.lv2/blob/4a14e641a328af51a36e24e00ad5f4f277ffd974/Makefile#L444-L457

**Comment by x42** [comment]
I see, git pull and try again.

Odd that it worked so far, perhaps in my case it worked due to lack of parallelism (default `-j1`)

**Comment by andistern** [comment]
git pull ( -> 0.9.18-4-g499916d ) & starting over was the perfect hint!
got a lot of deprecation warnings ( first deprecated in macOS 10.14 - OpenGL API deprecated. / is deprecated: first deprecated in macOS 10.12 ) / oh Apple !!!

finally necessary : brew install coreutils & changes in Makefile to use ginstall ...
hope to be able to create a PR ...

btw.: which install are you using?

thanks a lot!

**Comment by x42** [comment]
> btw.: which install are you using?

All dependent sources are compiled from scratch (no homebrew or mac-ports involved) on a pristine macOS system. Build starts with m4-1.4.18, gnu-make-4.1, autoconf-2.69, automake-1.14.1 ,...   The Intel 32/64 and PPC builds are done on OSX 10.6.8.  ARM/M1 are on compiled on macOS 11.2 (or 11.3.xx i have to check exact version).

**Comment by andistern** [comment]
I somehow spoiled my system by installing homebrew  - apple supplies a BSD - style install which fails with the -T option.

homebrew installs the GNU coreutils with a prepended `g' ( e.g. ginstall ) - thats why I edited the Makefile ( and am now enjoying the  15   "1/3 Octave Spectrum Analyzer" )
I am using macOS 11.4 (20F71),  GNU M4 1.4.6 ,  GNU Make 3.81 , autoconf (GNU Autoconf) 2.71 , automake (GNU automake) 1.16.4 - automake & autoconf installed by homebrew _and_ (g)install (GNU coreutils) 8.32 - instead of OS-supplied $FreeBSD: src/usr.bin/xinstall/xinstall.c,v 1.43 2001/05/30 07:08:49 ru Exp $

thanks again for your support & your software

**Comment by x42** [comment]
OK, so I understand you managed to compile and use these plugins, and this issue can be closed?

**Comment by andistern** [comment]
Quite shure - this issue can be closed !
