### ISSUE TITLE
SSE compiler flags only valid for x86

### ISSUE THREAD

**Issue by ehmry** [x42/meters.lv2#34]
https://github.com/x42/meters.lv2/blob/13750c7c8d19d5c9c7900736d93549d39f6f468b/Makefile#L13

**Comment by ehmry** [comment]
Fails to build for aarch64 NixOS: https://hydra.nixos.org/build/177130449.

**Comment by x42** [comment]
It's a make configuration variable, and the default is set to the most common value. In your case just run

`make OPTIMIZATIONS="-O3"`

or add optimizations suitable for the target architecture `-O3 -ffast-math -fomit-frame-pointer -fno-finite-math-only` or for armhf `O3 -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad`
