### ISSUE TITLE
Line Weight of Meter Needle

### ISSUE THREAD

**Issue by brucerothwell** [x42/meters.lv2#38]
Is it possible that a setting could be added that would the setting of the line weight of the meter needle -- as with the VU Meter -- so when you are using a smaller meter size, the needle can still be made to look "hefty" enough?

**Comment by x42** [comment]
Not easily.
The needle meter display does not have any state, and does not read any config information either.

However an easy solution would be to enforce a min. width of the needle.

**Comment by brucerothwell** [comment]
Perhaps just using the thickness used for the default size of the meter would be worth trying?Sent from my iPhoneOn Nov 30, 2023, at 10:51 AM, Robin Gareus ***@***.***> wrote:﻿
Not easily.
The needle meter display does not have any state, and does not read any config information either.
However an easy solution would be to enforce a min. width of the needle.

**Comment by brucerothwell** [comment]
Great — I’ll get the new plugin version downloaded and report back!Sent from my iPhoneOn Nov 30, 2023, at 11:31 AM, Robin Gareus ***@***.***> wrote:﻿

Perhaps just using the thickness used for the default size of the meter would be worth trying?

Yes, that is the case now (since  35 min ago).

**Comment by x42** [comment]
Great that it works for you now and thanks for bringing this issue to my attention.

I believe this issue can be closed now.
