### ISSUE TITLE
GUIs not drawing

### ISSUE THREAD

**Issue by unfa** [x42/meters.lv2#7]
After a recent update all my x42 meter plugins stopped to draw their interface. There are either black windows shown or some messed up pixmaps from X11 cache (I guess).
![bitmeter](https://cloud.githubusercontent.com/assets/491704/9016814/42e7afd8-37d4-11e5-9d91-6636d756929b.png)

This renders the entire plugin suite unusable.
Does anybody have the same problem?

**Comment by unfa** [comment]
Probably related: https://github.com/DISTRHO/ProM/issues/1

**Comment by unfa** [comment]
Also related: https://github.com/DISTRHO/MVerb/issues/1

**Comment by x42** [comment]
All x42-plugin GUIs are rendered using openGL.

This is most likely an issues with your X11/openGL setup (graphic card, driver, config). 

Does `glxgears` (test/demo app) run?  Please check the output of `glxinfo` that may shed some light.
Which linux distribution are you using?

**Comment by x42** [comment]
PS.  
> After a recent update..

update of your system or the plugins (or both)?

**Comment by unfa** [comment]
Both. I'm using Bubmlebee for OpenGL, and whehn I run the host application through optirun, it works fine. I had similar issue with other plugins rendered with OpenGL too.
