### ISSUE TITLE
Frequency/Phase wheel not drawing the points

### ISSUE THREAD

**Issue by unfa** [x42/meters.lv2#9]
![phase frequency wheel](https://cloud.githubusercontent.com/assets/491704/9291138/53c3b526-43b0-11e5-8b7f-d6c8eef4c1e5.png)

The grid and GUI is drawn all fine as well as the phase correlation meter, but the scope points are not drawn.

Possibly related to #8

**Comment by x42** [comment]
What signal level is fed into the meter? Could it simply be too low to show up? Try Normalize.
